### ISSUE TITLE
Package name

### ISSUE THREAD

**Issue by egoist** [egoist/vue-content-loader#1]
Not sure whether @alidcastano 's [vue-content-loader](https://github.com/alidcastano/vue-content-loader) is in use or not.

Otherwise I'll move this package to `@egoist/vue-content-loader` when I get the npm handle (egoist).

**Comment by alidcastano** [comment]
Im not using it :) not sure how to give away access tho 

I can look into it if you'd like handle

**Comment by egoist** [comment]
@alidcastano that's awesome, you can simply run `npm owner add rem vue-content-loader`

**Comment by alidcastano** [comment]
done

**Comment by egoist** [comment]
Thanks, published 😄

**Comment by ljiataday1** [comment]
hi，Online generation tool link 404, can you fix it?

**Comment by egoist** [comment]
ok seems it's changed to https://create-content-loader.now.sh/
