### ISSUE TITLE
Nuxtjs Example

### ISSUE THREAD

**Issue by iglimanaj** [egoist/vue-content-loader#154]
Hi,

Are you aware of any examples/demos for using `vue-content-loader` in a nuxt js project?

Best regards!

**Comment by LeBenLeBen** [comment]
@iglimanaj It should basically work the same, the only thing you have to do is to provide a unique value to the `uniqueKey` prop to prevent difference between server and client rendering. Did you encounter issues?

**Comment by Surya1995** [comment]
WARN  in ./node_modules/vue-content-loader/dist/vue-content-loader.es.js                                                                                       friendly-errors 02:05:48  

"export 'createVNode' was not found in 'vue'                                                                                                                    friendly-errors 02:05:48  
                                                                                                                                                                friendly-errors 02:05:48  

 WARN  in ./node_modules/vue-content-loader/dist/vue-content-loader.es.js                                                                                       friendly-errors 02:05:48  

"export 'defineComponent' was not found in 'vue'                                                                                                                friendly-errors 02:05:48  
                                                                                                                                                                friendly-errors 02:05:48  

 WARN  in ./node_modules/vue-content-loader/dist/vue-content-loader.es.js                                                                                       friendly-errors 02:05:48  

"export 'mergeProps' was not found in 'vue'

**Comment by LeBenLeBen** [comment]
@Surya1995 You’re using vue-content-loader ≥ 1.0.0 which is only compatible with Vue 3. Since Nuxt stable is based on Vue 2, you need to install `vue-content-loader@^0.2`.

**Comment by Surya1995** [comment]
@LeBenLeBen thanks working
