### ISSUE TITLE
Custom paths can't be rendered

### ISSUE THREAD

**Issue by cwiegleb** [egoist/vue-content-loader#17]
Hello,

I can't get this library to render custom paths with Vue 2.5. the clipPath is "undefined" in the HTML too, so I am not sure whats wrong.

Example used:

```
<content-loader
		:height="160"
		:width="400"
		:speed="2"
		primaryColor="#f3f3f3"
		secondaryColor="#ecebeb">
  <rect x="18.56" y="16.61" rx="0" ry="0" width="350.03" height="41" /> 
  <rect x="18.73" y="78.61" rx="0" ry="0" width="109.2" height="46" />
</content-loader>
```

if I inspect that, the clipPath is

```
<clipPath id="68y2z5o1l1d">undefined</clipPath>
```

Can you help?

**Comment by dombavetta** [comment]
I am facing the same issue.

**Comment by LeBenLeBen** [comment]
I cannot reproduce the issue with Vue 2.5.0 nor 2.5.22 using vue-content-loader 0.2.3. In any case you should upgrade Vue to the latest 2.x version. If that doesn’t fix the issue, please provide a reproduction link.
