### ISSUE TITLE
Online loader generator

### ISSUE THREAD

**Issue by egoist** [egoist/vue-content-loader#2]
It must be fun making a Vue version of http://danilowoz.com/create-react-content-loader/

**Comment by rabingaire** [comment]
I want to work on this 👍

**Comment by egoist** [comment]
@rabingaire Looking forward to it 😄

**Comment by rabingaire** [comment]
I will be working on my free time so It might take some time, I will let you know the progress though :)

**Comment by danilowoz** [comment]
@egoist Nice job! I really like your port to Vue!

So, about the creator, I was thinking to implement in the original project a tab with Vue support. 
I think it makes sense there is only one creator, therefore we can work together on the same features... I do have a lot of ideas to build new features, take a look issues in the projects...

I figure out something like this:
<img width="1552" alt="screen shot 2018-03-23 at 13 03 44" src="https://user-images.githubusercontent.com/4838076/37840368-a153500c-2e9b-11e8-8d47-b64f043b8c88.png">

Of course, we have to update the name of the project and kind stuff.

What do you think? I'll very glad to work together on this :)

**Comment by rabingaire** [comment]
Hey @egoist Look like I should get out of this since you already have react version, it would be good if you guys work together on this :)

**Comment by egoist** [comment]
@rabingaire @danilowoz Yep a `vue` tab on create-react-content-loader would be nice.

**Comment by egoist** [comment]
just realized that there's http://danilowoz.com/create-vue-content-loader/ now
