### ISSUE TITLE
Add option to control roundness of square blocks

### ISSUE THREAD

**Issue by TiGR** [egoist/vue-content-loader#357]
Some designs require square corners for loaders, but currently there is no way to do that with this component. Currently, `ry` and `rx` values in svg are hard-coded.

Could we have control over this value (either by two params or by one, controlling both values)?

**Comment by LeBenLeBen** [comment]
The predefined loaders are indeed not configurable as they are supposed to match a certain style. If you want to create custom layouts or alter the style more in depth, you can do so using the `ContentLoader`, for example:

````
<ContentLoader viewBox="0 0 250 100">
  <rect x="0" y="0" rx="0" ry="0" width="250" height="100" />
</ContentLoader>
```

You can easily make your own using [this tool](https://skeletonreact.com/) as well.
