### ISSUE TITLE
hope can support Inside container

### ISSUE THREAD

**Issue by bluelovers** [egoist/vue-content-loader#39]
like this
https://biigpongsatorn.github.io/#/vue-element-loading

![image](https://user-images.githubusercontent.com/167966/60359160-c7908b00-9a0a-11e9-9ff4-b1961584dc69.png)

**Comment by egoist** [comment]
A loading bar is actually different from a content loader like this, this is a placeholder for your content so you don't really need to render it on top of something else.

**Comment by LeBenLeBen** [comment]
@bluelovers It’s not clear for me what you’re expecting exactly. The goal of this library is not to provide overlays. You can easily achieve a similar effect with an extra HTML element around the loader with a few CSS properties.

If I misunderstood your request and what you want actually requires a change in this library, please clarify your needs 😃
