### ISSUE TITLE
 Uncaught TypeError: this.$slots.default is not a function

### ISSUE THREAD

**Issue by vojtys** [egoist/vue-content-loader#421]
Hi, I cant run loader with this configuration with custom loaders in slot.

```
"@vue/compat": "^3.1.5",
"@vue/compiler-sfc": "^3.1.5",
"@vue/composition-api": "^1.4.7",
"vue-content-loader": "^2.0.1",
"vue": "^3.1.5",
```

```
<content-loader v-if="visible" :speed="speed" :width="width" :height="height" primaryColor="#ced4da">
    <rect rx="3" ry="3" height="199" width="123" y="0" x="0"></rect>
</content-loader>
```

This fails with error:  **Uncaught TypeError: this.$slots.default is not a function**

**Comment by LeBenLeBen** [comment]
@vojtys Can you provide the whole stack trace? The file and lines around the error would help.

Note that `@vue/composition-api` should not be installed with Vue 3, it’s built-in.

**Comment by LeBenLeBen** [comment]
Since I cannot reproduce the issue with the given information, please provide a reproduction to reopen.
