### ISSUE TITLE
Skeletons animations are not working in the latest Chrome version

### ISSUE THREAD

**Issue by mdoesburg** [egoist/vue-content-loader#427]
See: https://github.com/danilowoz/react-content-loader/issues/316

**Comment by bilalmalkoc** [comment]
Same issue. Any solution @mdoesburg ?

**Comment by mdoesburg** [comment]
> Same issue. Any solution @mdoesburg ?

The library that this is based on has implemented a fix: https://github.com/danilowoz/react-content-loader/pull/317

The hope is that this library will also implement a fix. I currently don't have time to create a PR myself.

**Comment by mdoesburg** [comment]
Seems to be resolved.
