### ISSUE TITLE
Wrong height

### ISSUE THREAD

**Issue by leolux** [egoist/vue-content-loader#46]
The height of the rendered component is higher than the height set with `:height="200"`

**Comment by jsgv** [comment]
Experiencing the same. 
Setting the height to same size of window `window.innerHeight`

**Comment by knash94** [comment]
This was an issue for me when the loader was too wide for the parent container

**Comment by LeBenLeBen** [comment]
`width` and `height` props are used to set the SVG viewBox ratio, it does not hard code the dimensions on the element currently. I think in some cases it might be great to have different values.

My suggestion would be to get closer to what react-content-loader does:

- Keep `width` and `height` props but without default values, apply them as `width` and `height` attributes on the root SVG element if not empty
- Add a `viewBox` prop to be applied on the root SVG element, defaults to `0 0 {width} {height}` like it is now
- Warn if neither width/height nor viewBox props are provided
