### ISSUE TITLE
How to not responsive?

### ISSUE THREAD

**Issue by bagaskarala** [egoist/vue-content-loader#56]
How to make loader not-responsive, and not follow to be big, when container get bigger

**Comment by fcaivano** [comment]
You could try just adding a container (div) to the element and set a max-width to it.

**Comment by LeBenLeBen** [comment]
Starting from version 2, the SVG now comply to `width` and `height` attributes (as long as there is no CSS overriding them). See https://github.com/egoist/vue-content-loader#responsiveness
