### ISSUE TITLE
Component disappear during mount in nuxt

### ISSUE THREAD

**Issue by liqueflies** [egoist/vue-content-loader#6]
Hello,

thank you for the awesome work. I'm experiencing an issue using `vue-content-loader` with `nuxt`.
At the beginning server render the content, and then in mount it disappear.

If I trigger HMR component appear again.

Any ideas? 

Thank you.

**Comment by egoist** [comment]
Make sure to add a `uniqueKey` prop to your component: https://github.com/egoist/vue-content-loader#props

**Comment by alanPaivaAsp** [comment]
You could use NoSsr to render this on client-side, it worked for me

**Comment by tre-dev** [comment]
@egoist that's the correct answer and fixed it for me.
