### ISSUE TITLE
Online Tool

### ISSUE THREAD

**Issue by kleaSadiku** [egoist/vue-content-loader#64]
Online tool is not editable anymore,
It redirects me to: https://danilowoz.com/create-content-loader/ and I can only see and copy

**Comment by vkaelin** [comment]
+1, really annoying 😕

**Comment by egoist** [comment]
Seems you can only use UI controls to update the code now, maybe that's a design decision by @danilowoz ?

**Comment by vkaelin** [comment]
Yeah maybe, that's sad because we were much more precise with the old interface.

**Comment by danilowoz** [comment]
Hey, maintainer here.

Thanks for your feedback, but the live editor had so many bugs that it didn’t worth trying to solve. However, the new editor with input fields is much more precise and user-friendly.

<img width="690" alt="Screenshot 2020-03-05 at 11 54 12" src="https://user-images.githubusercontent.com/4838076/75979319-21b9e800-5ed8-11ea-881c-c3bf3e56f773.png">

**Comment by vkaelin** [comment]
The feature I'm currently missing is the ability to just paste an entire existing loader component into the live editor to make some little edits.

Thanks a lot for your work ! @danilowoz

**Comment by danilowoz** [comment]
Interesting, I haven't thought about it before, I'll take a look at how I can manage it on the current application. 

Cheers

**Comment by LeBenLeBen** [comment]
Please file issues and feature requests related to the editor on the dedicated repository: https://github.com/danilowoz/create-content-loader
