### ISSUE TITLE
why close sideEffects ?

### ISSUE THREAD

**Issue by sishenhei7** [egoist/vue-content-loader#67]
I see ```sideEffects: false``` in pkg settings。Can you tell me why ？

**Comment by sishenhei7** [comment]
sry, now i know why 0.0

**Comment by LeBenLeBen** [comment]
For anyone wondering, `sideEffects` is [used by webpack to leverage tree-shaking](https://webpack.js.org/configuration/optimization/#optimizationsideeffects).
