### ISSUE TITLE
Example for using vue-content-loader using CDN on webpage.

### ISSUE THREAD

**Issue by sarath49** [egoist/vue-content-loader#7]
Need an example for using vue-content-loader on simple html using cdn. No npm, no webpack, no yarn.

**Comment by sarath49** [comment]
Inside your new Vue instance create a component:
```
new Vue({
 el: '#root',
components: {
 'content-loader':  window.contentLoaders.FacebookLoader
} 
});
```
After that in your html:
```
<div id="root">
  <template >
				<content-loader>
				</content-loader>
		</template>
</div>
```
This way you can show Facebook style loader in you web page while using CDN.

**Comment by diegotejadav** [comment]
Hey @sarath49, thank you for sharing the solution, it was very helpful to me 😄
