### ISSUE TITLE
Seems to show a black color an iPhone8 plus

### ISSUE THREAD

**Issue by iyanming** [egoist/vue-content-loader#76]
`<ContentLoader
      :height="960"
      :width="700"
    >`
This is the code causing the problem.
But i fix it by 
`<ContentLoader
      :height="960"
      :width="701"
    >`
Then,it looks like normal.
why?I think it is a bug.
![tmp7cfe04ab](https://user-images.githubusercontent.com/23701391/81680771-34c3d800-9486-11ea-870f-ccbfe6037776.png)

**Comment by iyanming** [comment]
@egoist @719media @laFreeFall @emilpriver

**Comment by pimvanderheijden** [comment]
Anybody knows if this is still the case?

**Comment by LeBenLeBen** [comment]
@iyanming I cannot reproduce on iOS 14.3.

Can you please specify on which iOS version you’re seeing this issue and provide the code you used for this component?

**Comment by LeBenLeBen** [comment]
I’ll reopen and investigate if one can provide a reproduction link.
