### ISSUE TITLE
content-loader not displayed immediately when in production

### ISSUE THREAD

**Issue by nazreen** [egoist/vue-content-loader#8]
before introducing content-loader I just had a loading spinner that would appear immediately upon arriving on a certain page

after replacing the loading spinner with content-loader, there is a lag for the content-loader to appear. are there known causes to this?

this problem appears only in production, but not when I am running my development server.

**Comment by egoist** [comment]
A repro please, like a jsfiddle or a codesandbox example

**Comment by lourdrivera123** [comment]
Are you using Nuxt @nxmohamad  ?

**Comment by nxmohamad** [comment]
@lourdrivera123  I'm not. It's a project set up using https://github.com/vuejs-templates/webpack

**Comment by LeBenLeBen** [comment]
I don’t see what could cause this from within the library. However the browser being busy on rendering other stuff could delay the animation, some slower network requests could impact your component logic & rendering as well as CSS influence the SVG display.

I don’t think I can help you further without a reproduction link, please provide one if you need any more help.
