### ISSUE TITLE
Is this project still alive

### ISSUE THREAD

**Issue by bistory** [egoist/vue-content-loader#91]
Hi,

I ask that painful question because pull requests are still pending, bugs from a few months have no reply...

Maybe you need some help maintaining this project or you don't use it anymore ?

BTW I don't see any active alternative in the Vue.js world so this project still seems to be the best choice 👍 

Thanks for your efforts in creating this package, I hope you will reply to this ticket ;-)

**Comment by egoist** [comment]
Yeah new maintainers are welcome, ping me if anyone wants to help this project.

**Comment by LeBenLeBen** [comment]
Yes it is 😃
